sonar.host.url=https://sonarcloud.io
sonar.organization=knauf-group
sonar.projectKey=Knauf-Group_kul-okta-config
sonar.projectName=kul-okta-config
sonar.projectDescription=Knauf Okta Config using Terraform
sonar.projectVersion=1.0
sonar.sources=devops,scripts,services
sonar.links.scm=https://github.com/Knauf-Group/kul-okta-config
