###################################################################
# IMPORTANT: make sure admins have `APP_ADMIN` role!
# Check administrators configuration.
###################################################################
---
{}
