@startuml
'https://plantuml.com/sequence-diagram

skinparam sequence {
    ArrowColor black
    ActorBorderColor BACBFC
    ActorBackgroundColor BACBFC
    LifeLineBorderColor blue
    LifeLineBackgroundColor lightblue

    ParticipantBorderColor D6E0FD
    ParticipantBackgroundColor D6E0FD
}
skinparam NoteBackgroundColor SmokeWhite

autonumber
== access backend service (api) for logged in user ==

actor User
participant "Frontend\n(Browser)" as Frontend
participant "NextJs Backend\n(NextAuth)" as NextBackend

participant "API\n(ResourceServer)" as API

User -> Frontend: Open restricted page
activate Frontend
Frontend -> NextBackend: get session
activate NextBackend
NextBackend -> Frontend: return session
Frontend -> NextBackend: API request\n(session cookie)
note right: claim uid = okta id

NextBackend -> API: API request\n(access token\n in bearer header)
activate API
API -> NextBackend: API response
deactivate API
NextBackend -> Frontend: API response
deactivate NextBackend

Frontend -> User: Display data from backend
deactivate Frontend

@enduml
